name: Generate Wiki
author: MikhaD
description: >-
  Create a wiki from one or more folders of markdown files, with the option to generate a custom
  sidebar from th =e directory structure of the source files.

inputs:
  folders:
    description: >-
      The directory or list of folders to generate the wiki from. Default is wiki. If you wish to
      include multiple directories, separate them with a comma (wiki, docs etc.).
    default: "wiki"
  sidebar:
    description: >-
      Whether or not you wish to generate a custom sidebar with categories based on the
      subdirectories of the input directory. Defaults to true.
    default: "true"
  prefix-files-with-dir:
    description: >-
      Whether or not to prefix file names with the directory they are in. This can be useful if you
      have multiple files with the same name in different directories, as github wikis completely
      ignore subdirectories and flatten everything out. Prefixed files will be named
      dir|filename.ext. Defaults to false.
    default: "false"
  branch-to-link-to:
    description: >-
      The branch to link to when wiki files link to code, images etc. Defaults to the default branch
      of the repository.
    default: ${{ github.event.repository.default_branch }}
  clear-wiki:
    description: >-
      Whether or not to clear the wiki before generating the new files. Defaults to
      false. This is useful if you do not want wiki pages from anywhere other than this action.
    default: "false"
  edit-warning:
    description: >-
      Whether or not to include a warning comment at the top of each generated file telling the
      viewer not to edit it and pointing them to the source file to edit instead. Defaults to true.
    default: "true"
  token:
    description: >-
      The token to use to authenticate with the repository. This is required if you want to push
      changes to the wiki.
    required: true
    default: ${{ github.token }}
  host:
    description: Could this be the issue?
    required: true
    default: ${{ github.server_url }}
  generated-files-dir:
    description: >-
      The directory in the wiki repository to store the generated files in. Defaults to generated.
      This is useful because it allows you to keep the generated files separate from any other files
      in the wiki, such as those created by users.
    default: "generated"
  sections-open-depth:
    description: >-
      The depth of the sidebar sections to be open by default. Defaults to 1. This means that all
      top level sections will be open, but any subsections will be closed. Setting this to 0 will
      close all sections by default. Setting this to -1 will open all sections by default.
    default: "1"
  make-wiki-dirs-sections:
    description: >-
      Whether or not to make the directories the wiki is being generated from into sections in the
      sidebar. Defaults to false. If this is true and sidebar is true, if the wiki is being created
      from a directory called wiki, the sidebar will have a section called wiki with all the files
      from that directory in it. If this is false and sidebar is true, the files in the root of wiki
      will be in the root of the sidebar.
    default: "false"

runs:
  using: node20
  main: dist/bundle.cjs
