name: Issue event

on: issues

jobs:
  update:
    name: Update Upcoming Features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: This action
        uses: ./