name: Generate Wiki

on:
  push:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/wiki.yml


jobs:
  generate-wiki:
    name: Generate wiki from docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: wiki-from-folder
        uses: ./
        with:
            folders: docs
            clear-wiki: true