name: Generate Wiki

on:
  push:
    branches: [main]



jobs:
  update:
    name: Generate wiki from docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: npm ci

      - name: This action
        uses: ./
        with:
            folders: "docs"
            prefix-files-with-directory: false
            clear-wiki: true
            token: ${{ secrets.GITHUB_TOKEN }}